### ISSUE TITLE
Fix carthage search paths added when no dependencies are present.

### ISSUE THREAD

**Issue by pmairoldi** [petester42/framework-generate#11]
Right now if you don't specify any dependencies that are carthage, the tool still adds the search paths. This causes a build issues at least in Xcode 9

**Comment by sunshinejr** [comment]
@petester42 I'm not sure if this one is fixed yet. Search paths are still added when creating new platform - even though there are no dependencies.

**Comment by pmairoldi** [comment]
Doh. Yes of course.

**Comment by pmairoldi** [comment]
Should be fixed in 1.3.2

**Comment by sunshinejr** [comment]
I checked it and it works perfectly, both phase and build paths are not added, thanks again @petester42!
