### ISSUE TITLE
Copy Carthage Frameworks phase

### ISSUE THREAD

**Issue by sunshinejr** [petester42/framework-generate#12]
Hey @petester42. There is [additional build_phase](https://github.com/petester42/framework-generate/blob/master/lib/framework-generate/target.rb#L308) added for test target type, even if the library does not use Carthage dependencies (might be connected to #11). Would be awesome if we could get rid of that one either by command or with a deps.count check.

**Comment by pmairoldi** [comment]
Ya it’s related to #11. I’ll look into it again.

**Comment by pmairoldi** [comment]
Version 1.3.1 should fix this!

**Comment by sunshinejr** [comment]
Thanks @petester42!
