### ISSUE TITLE
Specify carthage directory path

### ISSUE THREAD

**Issue by tbaranes** [petester42/framework-generate#3]
If the Xcodeproj isn't in the root directory (as well as the carthage directory), the generated `framework search path` will be invalid. I didn't find a way to set a custom carthage path from the docs, would be a great option!

**Comment by tbaranes** [comment]
In the end, I'm using `search_paths` directly like this:

```
carthage_path = "${SRCROOT}/../Carthage/Build"
platforms = [
    macos("10.11", search_paths = "#{carthage_path}/Mac/"),
    ios("9.0", search_paths = "#{carthage_path}/iOS/"),
    tvos("9.0"),
    watchos("2.0")
]
```

It's working as expected, so closing this, my bad to miss that feature!

**Comment by pmairoldi** [comment]
No problem. Do you think the documentation is lacking in this section?

**Comment by tbaranes** [comment]
Personally, I miss it  because I didn't the usage in ruby, so it was more due to my missing knowledge than the documentation itself.

It may be harder to get everything for new ruby users, but I don't think it's an issue
