### ISSUE TITLE
Gather coverage data option.

### ISSUE THREAD

**Issue by sunshinejr** [petester42/framework-generate#7]
Hey @petester42. I'm wondering if you could introduce `Gather coverage data` option to the script. In [#1169](https://github.com/Moya/Moya/pull/1169), we figured that now when you have this option selected in the main scheme, and you are using Xcode 9, the build won't pass the submission. Thus we would like to enable it only in MoyaTests scheme. Would it be possible? Or maybe you have another idea?

**Comment by pmairoldi** [comment]
Shouldn't be too hard. I'll look at what possible and come back to you. Isn't this just an Xcode 9 beta bug though?

**Comment by sunshinejr** [comment]
Thank you! I'm not sure if this is a bug or a feature of Xcode 9 beta, but I came to a conclusion that we don't really need the coverage outside of MoyaTests anyways - what do you think about it?

**Comment by pmairoldi** [comment]
closed by #8

**Comment by akac** [comment]
I'm still having this issue myself - was this actually resolved for Xcode 9?

**Comment by pmairoldi** [comment]
It should be. I haven't tested publishing to the App Store but now by default the coverage data is off. Are you using 1.2.1?

**Comment by akac** [comment]
Well I just grabbed it yesterday - and my first TF build with Charts got called out for that. I opened the project and it was in the scheme. Its commit e72f28061eea69f6dcb1b684b709946f50c87610

**Comment by pmairoldi** [comment]
Well maybe it's not your project's fault. I don't think the charts project has been updated for Xcode 9 since I haven't merge #10 yet.
